apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vcgateway.fullname" . }}
  labels:
  {{- include "vcgateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  client-id: {{ .Values.configuration.clientId  | quote }}
  client-secret: {{ .Values.configuration.clientSecret  | quote }}
  ecdh-private-key: {{ .Values.configuration.ecdhPrivateKey  | quote }}