apiVersion: v1
kind: Service
metadata:
  name: {{ include "vcgateway.fullname" . }}
  labels:
    {{- include "vcgateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
{{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
{{- end }}
  ports:
    - port: {{ .Values.service.bpa.port }}
      targetPort: {{ .Values.service.bpa.targetPort }}
      protocol: TCP
      name: bpa
  {{- if .Values.service.debug.targetPort }}
    - port: {{ .Values.service.debug.port }}
      targetPort: {{ .Values.service.debug.targetPort }}
      protocol: TCP
      name: debug
  {{- end }}
  selector:
    {{- include "vcgateway.selectorLabels" . | nindent 4 }}
